# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'home_work_2_month_5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'

end
